name: {{project_name.snakeCase()}}
description: starter template made by @jslattery26
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #firebase
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_remote_config: ^3.0.9
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  cloud_functions: ^4.0.7
  firebase_analytics: ^10.1.0
  firebase_crashlytics: ^3.0.11
  firebase_messaging: ^14.2.1

  #riverpod-hooks-freezed
  hooks_riverpod: ^2.1.3
  flutter_hooks: ^0.18.5+1
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  flutter_use: ^0.0.3

  #essentials
  logger: ^1.1.0
  uuid: ^3.0.7
  shared_preferences: ^2.0.16
  encrypt: ^5.0.1
  http: ^0.13.5
  go_router: ^6.0.1
  device_preview: ^1.1.0
  dynamic_color: ^1.5.4
  device_info_plus: ^8.0.0

  #you can remove this when you're done with it
  rename: ^2.1.1
  package_rename: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  flutter_native_splash: ^2.2.11
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
